services:
  # 1. フロントエンド
  frontend:
    image: drug-order-frontend:latest
    container_name: drug-order-frontend
    restart: always
    # 本番では開発サーバー(npm start)ではなくビルド後の静的配信が理想ですが、
    # 現状のDockerfileのまま動かす場合は npm start が走ります。
    # ソースコードのマウント(- ./frontend:/app)は削除し、イメージ内のコードを使用させます。
    ports:
      - "3000:3000"  # Nginx経由でなく直接確認する場合用。Nginxのみなら不要な場合も。
    networks:
      - frontend-network
    environment:
      - TZ=Asia/Tokyo

  # 2. バックエンド
  backend:
    image: drug-order-backend:latest
    container_name: drug-order-backend
    restart: always
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production  # 本番モードに変更
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=drug_order_db
      - TZ=Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    # ソースコードのマウント(- ./backend:/app)は削除
    networks:
      - backend-network

  # 3. データベース
  db:
    image: mysql:8.4
    container_name: drug-order-db
    restart: always
    environment:
      - MYSQL_DATABASE=drug_order_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # 初期化SQLが必要な場合は、そのファイルだけは本番機に配置してマウントするか、
      # 事前にイメージにCOPYするDockerfileを作る必要があります。
      # 今回は「initフォルダを本番機に置く」想定で記述を残します。
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  # 4. Webサーバー
  webserver:
    image: nginx:1.25
    container_name: drug-order-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # 設定ファイルは本番機に配置してマウントします
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - frontend-network
      - backend-network
    environment:
      - TZ=Asia/Tokyo

volumes:
  db_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge