"""empty message

Revision ID: 2db18432e713
Revises: 5caf597f210d
Create Date: 2025-12-05 11:23:17.125228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db18432e713'
down_revision = '5caf597f210d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegrams',
    sa.Column('id_', sa.String(length=30), nullable=False, comment='doc_id'),
    sa.Column('patient_id', sa.String(length=20), nullable=True, comment='Patient ID'),
    sa.Column('patient_name', sa.String(length=100), nullable=True, comment='Patient Kanji Name'),
    sa.Column('order_number', sa.Integer(), nullable=True, comment='Order Number'),
    sa.Column('order_version', sa.Integer(), nullable=True, comment='Order Version'),
    sa.Column('order_date', sa.String(length=20), nullable=True, comment='Order Date (YYYYMMDD)'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Parsed Raw JSON Data'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Created At'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Updated At'),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegrams_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegrams_patient_id'))

    op.drop_table('telegrams')
    # ### end Alembic commands ###
