"""empty message

Revision ID: 5caf597f210d
Revises: ffb70c78964d
Create Date: 2025-12-05 08:09:15.756675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5caf597f210d'
down_revision = 'ffb70c78964d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_', sa.String(length=30), nullable=False, comment='doc_id'))
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=True, comment='Order Number'))
        batch_op.add_column(sa.Column('order_version', sa.Integer(), nullable=True, comment='Order Version'))
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='Patient ID',
               existing_comment='患者番号',
               existing_nullable=True)
        batch_op.alter_column('patient_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='Patient Kanji Name',
               existing_comment='患者漢字氏名',
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=mysql.VARCHAR(length=20),
               comment='Order Date (YYYYMMDD)',
               existing_comment='オーダ日付(YYYYMMDD)',
               existing_nullable=True)
        batch_op.alter_column('raw_data',
               existing_type=mysql.JSON(),
               comment='Parsed Raw JSON Data',
               existing_comment='解析済み電文データ全文',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='Created At',
               existing_comment='登録日時',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='Updated At',
               existing_comment='更新日時',
               existing_nullable=True)
        batch_op.drop_column('id')
        batch_op.drop_column('system_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_code', mysql.VARCHAR(length=10), nullable=True, comment='送信先システムコード'))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新日時',
               existing_comment='Updated At',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='登録日時',
               existing_comment='Created At',
               existing_nullable=True)
        batch_op.alter_column('raw_data',
               existing_type=mysql.JSON(),
               comment='解析済み電文データ全文',
               existing_comment='Parsed Raw JSON Data',
               existing_nullable=True)
        batch_op.alter_column('order_date',
               existing_type=mysql.VARCHAR(length=20),
               comment='オーダ日付(YYYYMMDD)',
               existing_comment='Order Date (YYYYMMDD)',
               existing_nullable=True)
        batch_op.alter_column('patient_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='患者漢字氏名',
               existing_comment='Patient Kanji Name',
               existing_nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='患者番号',
               existing_comment='Patient ID',
               existing_nullable=True)
        batch_op.drop_column('order_version')
        batch_op.drop_column('order_number')
        batch_op.drop_column('id_')

    # ### end Alembic commands ###
