"""initial migration

Revision ID: 82651e4317e3
Revises: 
Create Date: 2025-12-03 06:19:07.164735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82651e4317e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegrams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=True, comment='患者番号'),
    sa.Column('patient_name', sa.String(length=100), nullable=True, comment='患者漢字氏名'),
    sa.Column('order_date', sa.String(length=20), nullable=True, comment='オーダ日付(YYYYMMDD)'),
    sa.Column('system_code', sa.String(length=10), nullable=True, comment='送信先システムコード'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='解析済み電文データ全文'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='登録日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegrams_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegrams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegrams_patient_id'))

    op.drop_table('telegrams')
    # ### end Alembic commands ###
